apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- order-service-deployment.yaml
- order-service-service.yaml
- order-db-statefulset.yaml
- order-db-service.yaml
- inventory-service-deployment.yaml
- inventory-service-service.yaml
- inventory-db-statefulset.yaml
- inventory-db-service.yaml
- api-gateway-deployment.yaml
- api-gateway-service.yaml
images:
- name: api-gateway
  newName: laurefindele/api-gateway
- name: inventory-service
  newName: laurefindele/inventory-service
- name: order-service
  newName: laurefindele/order-service